version: 2.1
jobs:
    test:
        machine:
            image: 'ubuntu-1604:201903-01'
        steps:
            # Checking out code
            - checkout
            # Installing node
            - run: 
                command: |
                    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
                    export NVM_DIR="/opt/circleci/.nvm"
                    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            - run: nvm install node
            - run: nvm use node
            # Installing Packages
            - run: npm install
            # Installing Mongo
            - run: sudo apt-get install gnupg
            - run: wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add -
            - run: echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.4.list
            - run: sudo apt-get update
            - run: sudo apt-get install -y mongodb-org
            - run: sudo service mongod start
            # Run Tests
            - run: npm run test
orbs:
    node: circleci/node@4.0.0
workflows:
    test:
        jobs:
            - test
